"""Domain layer: contracts, state machine, editor-gate policy, Masthead registry."""

from newsroom_fleet.domain.contracts import (
    Article,
    Claim,
    ClaimSnapshot,
    ClaimType,
    Desk,
    EditorDecision,
    EditorDisposition,
    EvidenceRef,
    Materiality,
    RiskTier,
    Role,
    SecurityDisposition,
    SecurityResult,
    Source,
    Verdict,
    VerdictResult,
    WatcherResult,
    WatcherStatus,
)
from newsroom_fleet.domain.masthead import MASTHEAD, masthead_view, registration_for
from newsroom_fleet.domain.policy import (
    ClaimAssessment,
    GateReport,
    PublishDecision,
    assess_claim,
    decide_publish,
    evaluate_gate,
)
from newsroom_fleet.domain.state_machine import (
    IllegalTransitionError,
    PublicationState,
    can_transition,
    transition,
)

__all__ = [
    "MASTHEAD",
    "Article",
    "Claim",
    "ClaimAssessment",
    "ClaimSnapshot",
    "ClaimType",
    "Desk",
    "EditorDecision",
    "EditorDisposition",
    "EvidenceRef",
    "GateReport",
    "IllegalTransitionError",
    "Materiality",
    "PublicationState",
    "PublishDecision",
    "RiskTier",
    "Role",
    "SecurityDisposition",
    "SecurityResult",
    "Source",
    "Verdict",
    "VerdictResult",
    "WatcherResult",
    "WatcherStatus",
    "assess_claim",
    "can_transition",
    "decide_publish",
    "evaluate_gate",
    "masthead_view",
    "registration_for",
    "transition",
]
