"""Repository protocol — the seam where Firestore slots in later.

The local implementation is SQLite. All durable pipeline state (articles,
claims, verdicts, security results, decisions, snapshots, watcher results,
audit events) flows through this interface; desks never touch it.
"""

from __future__ import annotations

from typing import Protocol

from newsroom_fleet.domain.contracts import (
    Article,
    Claim,
    ClaimSnapshot,
    EditorDecision,
    SecurityResult,
    Verdict,
    WatcherResult,
)
from newsroom_fleet.domain.state_machine import PublicationState
from newsroom_fleet.persistence.events import AuditEvent


class Repository(Protocol):
    # Articles
    def save_article(self, article: Article, state: PublicationState) -> None: ...
    def get_article(
        self, article_id: str
    ) -> tuple[Article, PublicationState, str | None] | None: ...
    def list_articles(self) -> list[str]: ...
    def set_state(self, article_id: str, state: PublicationState) -> None: ...
    def set_published_text(self, article_id: str, text: str) -> None: ...

    # Claims
    def save_claims(self, claims: list[Claim]) -> None: ...
    def get_claims(self, article_id: str) -> list[Claim]: ...

    # Verdicts (idempotent: one persisted verdict per (article_id, claim_id,
    # desk) — claim ids are unique per article, not globally; an ERROR verdict
    # may be replaced by a later healthy run)
    def save_verdict(self, verdict: Verdict) -> bool: ...
    def get_verdict(self, article_id: str, claim_id: str, desk: str) -> Verdict | None: ...
    def get_article_verdicts(self, article_id: str) -> list[Verdict]: ...

    # Security results
    def save_security_results(self, results: list[SecurityResult]) -> None: ...
    def get_security_results(self, article_id: str) -> list[SecurityResult]: ...

    # Editor decisions
    def save_decision(self, decision: EditorDecision) -> None: ...
    def get_decision(self, decision_id: str) -> EditorDecision | None: ...
    def get_decisions(self, article_id: str) -> list[EditorDecision]: ...

    # Published snapshots (for the watcher)
    def save_snapshot(self, snapshot: ClaimSnapshot) -> None: ...
    def get_snapshots(self, article_id: str) -> list[ClaimSnapshot]: ...

    # Watcher results
    def save_watcher_result(self, result: WatcherResult) -> None: ...
    def get_watcher_results(self, article_id: str) -> list[WatcherResult]: ...
    def dispose_watcher_result(self, watcher_id: str) -> None: ...

    # Audit trail (append-only)
    def append_event(self, event: AuditEvent) -> None: ...
    def get_events(self, article_id: str) -> list[AuditEvent]: ...

    # Demo support
    def reset(self) -> None: ...
